INSERT INTO medications (name, description, requires_refrigeration, weight_grams, stock_quantity)
VALUES
('Paracetamol 500mg', 'Pain relief and fever reduction', FALSE, 50, 100),
('Ibuprofen 400mg', 'Anti-inflammatory pain relief', FALSE, 60, 80),
('Insulin (Humalog)', 'Fast-acting insulin for diabetes', TRUE, 30, 50),
('Amoxicillin 500mg', 'Antibiotic for bacterial infections', FALSE, 70, 60),
('Salbutamol Inhaler', 'Asthma relief inhaler', FALSE, 45, 40),
('Aspirin 75mg', 'Blood thinner for heart health', FALSE, 40, 90),
('Omeprazole 20mg', 'Reduces stomach acid', FALSE, 55, 70),
('Metformin 500mg', 'Controls blood sugar levels in type 2 diabetes', FALSE, 65, 120),
('Prednisolone 5mg', 'Steroid for reducing inflammation', FALSE, 50, 90),
('Levothyroxine 50mcg', 'Thyroid hormone replacement', FALSE, 30, 110),
('Cetirizine 10mg', 'Antihistamine for allergy relief', FALSE, 40, 95),
('Loratadine 10mg', 'Treatment for hay fever and allergic reactions', FALSE, 40, 85),
('Clarithromycin 250mg', 'Antibiotic for bacterial infections', FALSE, 70, 60),
('Insulin (Lantus)', 'Long-acting insulin for diabetes', TRUE, 25, 40),
('Insulin (Novorapid)', 'Rapid-acting insulin', TRUE, 25, 50),
('Vitamin D3 1000IU', 'Supports bone and immune health', FALSE, 35, 200),
('Vitamin B12 1000mcg', 'B12 deficiency treatment', FALSE, 30, 150),
('Folic Acid 400mcg', 'Promotes red blood cell formation', FALSE, 30, 140),
('Atorvastatin 20mg', 'Lowers cholesterol levels', FALSE, 50, 100),
('Simvastatin 10mg', 'Cholesterol reduction medication', FALSE, 45, 85),
('Ramipril 5mg', 'Treats high blood pressure', FALSE, 50, 100),
('Amlodipine 10mg', 'Calcium channel blocker for hypertension', FALSE, 55, 90),
('Losartan 50mg', 'Angiotensin receptor blocker for hypertension', FALSE, 60, 80),
('Bisoprolol 2.5mg', 'Beta-blocker for heart conditions', FALSE, 40, 75),
('Propranolol 10mg', 'Beta-blocker for anxiety and heart issues', FALSE, 40, 70),
('Sertraline 50mg', 'Antidepressant (SSRI)', FALSE, 50, 95),
('Fluoxetine 20mg', 'Antidepressant for mood disorders', FALSE, 45, 100),
('Citalopram 20mg', 'SSRI antidepressant', FALSE, 45, 85),
('Diazepam 5mg', 'Anxiety and muscle spasm relief', FALSE, 40, 60),
('Lorazepam 1mg', 'Short-acting benzodiazepine', FALSE, 35, 40),
('Codeine 30mg', 'Opioid pain reliever', FALSE, 45, 50),
('Morphine Sulfate 10mg', 'Strong opioid pain medication', FALSE, 50, 30),
('Tramadol 50mg', 'Moderate pain relief', FALSE, 55, 80),
('Gabapentin 300mg', 'Nerve pain and seizure control', FALSE, 70, 65),
('Pregabalin 75mg', 'Treats nerve pain and anxiety', FALSE, 65, 70),
('Naproxen 250mg', 'Anti-inflammatory medication', FALSE, 60, 90),
('Hydrocortisone Cream 1%', 'Topical steroid for skin irritation', FALSE, 30, 140),
('Clotrimazole Cream 2%', 'Antifungal cream', FALSE, 35, 130),
('Ketoconazole Shampoo 2%', 'Anti-dandruff and antifungal shampoo', FALSE, 120, 40),
('Erythromycin 250mg', 'Antibiotic for acne and infections', FALSE, 70, 50),
('Doxycycline 100mg', 'Broad-spectrum antibiotic', FALSE, 65, 60),
('Ciprofloxacin 500mg', 'Strong antibiotic for infections', FALSE, 75, 50),
('Azithromycin 250mg', 'Antibiotic used in short courses', FALSE, 60, 80),
('Warfarin 3mg', 'Anticoagulant to prevent clots', FALSE, 30, 40),
('Apixaban 5mg', 'Blood thinner for stroke prevention', FALSE, 35, 60),
('Rivaroxaban 10mg', 'Anticoagulant for DVT and PE', FALSE, 35, 60),
('Salicylic Acid Gel 12%', 'Acne and wart treatment', FALSE, 25, 100),
('Aciclovir 400mg', 'Antiviral for cold sores', FALSE, 60, 70),
('Oseltamivir 75mg', 'Antiviral flu medication', FALSE, 50, 40),
('Nitrofurantoin 100mg', 'Urinary tract infection treatment', FALSE, 55, 60),
('Loperamide 2mg', 'Anti-diarrhoeal medication', FALSE, 40, 120),
('Oral Rehydration Salts', 'Hydration electrolyte solution', FALSE, 35, 200),
('Simeticone 80mg', 'Relieves trapped wind and bloating', FALSE, 30, 140),
('Ranitidine 150mg', 'Reduces stomach acid', FALSE, 50, 80),
('Gaviscon Liquid 200ml', 'Relieves heartburn and reflux', FALSE, 200, 50),
('Saline Nasal Spray 0.9%', 'Moisturises dry nasal passages', FALSE, 100, 100),
('Beclomethasone Inhaler', 'Steroid inhaler for asthma', FALSE, 45, 40),
('Fluticasone Nasal Spray', 'Relieves hay fever symptoms', FALSE, 50, 60),
('Montelukast 10mg', 'Asthma prevention medication', FALSE, 40, 70),
('Adrenaline Auto-Injector', 'Emergency treatment for anaphylaxis', FALSE, 60, 35),
('Vitamin C 500mg', 'Immune support supplement', FALSE, 40, 160),
('Ferrous Sulfate 200mg', 'Iron supplement for anaemia', FALSE, 50, 150),
('Zinc 10mg', 'Mineral supplement', FALSE, 30, 140),
('Magnesium Oxide 400mg', 'Supports nerve and muscle function', FALSE, 55, 100),
('Co-codamol 8/500mg', 'Combination analgesic', FALSE, 55, 120),
('Baclofen 10mg', 'Muscle relaxant', FALSE, 50, 70),
('Mirtazapine 15mg', 'Antidepressant for mood disorders', FALSE, 45, 60),
('Amitriptyline 10mg', 'Low-dose nerve pain medication', FALSE, 40, 70),
('Quetiapine 25mg', 'Antipsychotic for mood stabilisation', FALSE, 50, 40),
('Olanzapine 5mg', 'Antipsychotic for schizophrenia', FALSE, 40, 35),
('Metoclopramide 10mg', 'Reduces nausea and vomiting', FALSE, 40, 80),
('Ondansetron 4mg', 'Anti-nausea medication', FALSE, 35, 60),
('Hyoscine Butylbromide 10mg', 'Relieves stomach cramps', FALSE, 40, 90),
('Diclofenac Gel 1%', 'Topical anti-inflammatory gel', FALSE, 35, 90),
('Lidocaine Patch 5%', 'Local anaesthetic for pain relief', FALSE, 25, 40),
('Benzoyl Peroxide 5%', 'Acne treatment gel', FALSE, 30, 80),
('Sodium Chloride IV 0.9%', 'Fluid for IV hydration', TRUE, 500, 30),
('Potassium Chloride IV', 'Electrolyte IV solution', TRUE, 400, 25),
('Adrenaline 1mg/1ml', 'Emergency cardiac medication', TRUE, 10, 35),
('Heparin 5000IU', 'Anticoagulant for clot prevention', TRUE, 15, 50),
('Insulin (Tresiba)', 'Ultra-long-acting insulin', TRUE, 25, 35),
('Procaine Penicillin', 'Injectable antibiotic', TRUE, 30, 40),
('Epinephrine 1mg', 'Emergency medication for cardiac arrest', TRUE, 10, 20),
('Gentamicin Injection', 'Hospital-grade antibiotic', TRUE, 20, 25),
('Labetalol 100mg', 'Blood pressure control medication', FALSE, 45, 60),
('Spironolactone 25mg', 'Diuretic for heart failure', FALSE, 50, 55),
('Furosemide 20mg', 'Diuretic for fluid retention', FALSE, 50, 70),
('Calcium Carbonate 500mg', 'Calcium supplement', FALSE, 60, 120),
('Activated Charcoal Capsules', 'Treats poisoning and bloating', FALSE, 40, 100),
('Isotretinoin 20mg', 'Severe acne treatment', FALSE, 35, 30),
('Tretinoin Cream 0.05%', 'Topical acne treatment', FALSE, 25, 40),
('Melatonin 3mg', 'Sleep regulation supplement', FALSE, 30, 80),
('Nicotine Patch 21mg', 'Smoking cessation support', FALSE, 20, 100),
('Glyceryl Trinitrate Spray', 'Relieves angina symptoms', FALSE, 35, 40),
('Sodium Bicarbonate Tablets', 'Relieves indigestion', FALSE, 50, 90),
('Chloramphenicol Eye Drops', 'Antibiotic eye treatment', FALSE, 20, 60),
('Artificial Tears', 'Lubricating eye drops', FALSE, 20, 150),
('Dextromethorphan Syrup', 'Cough suppressant', FALSE, 150, 70),
('Guaifenesin 200mg', 'Expectorant for chest congestion', FALSE, 70, 100),
('Ibuprofen Gel 5%', 'Topical anti-inflammatory gel', FALSE, 30, 80),
('Multivitamin Tablets', 'General nutritional supplement', FALSE, 50, 200),
('Electrolyte Powder', 'Dissolvable hydration powder', FALSE, 20, 180),
('Oral Glucose Gel', 'Rapid blood sugar increase', FALSE, 25, 120);
